---
coredns_port: 53
coredns_config: |
  noisebridge.com {
    file zones/noisebridge.com {
      # ns1.noisebridge.net (m3.noisebridge.net)
      transfer to 216.252.162.220
      transfer to 2602:ff06:725:5:dc::1337
      # ns2.noisebridge.net (m4.noisebridge.net)
      transfer to 204.246.122.84
      transfer to 2602:ff06:677:4:54::1337
    }
    prometheus
    errors
  }
  noisebridge.net {
    file zones/noisebridge.net {
      # ns1.noisebridge.net (m3.noisebridge.net)
      transfer to 216.252.162.220
      transfer to 2602:ff06:725:5:dc::1337
      # ns2.noisebridge.net (m4.noisebridge.net)
      transfer to 204.246.122.84
      transfer to 2602:ff06:677:4:54::1337
    }
    dnssec noisebridge.net {
      key file keys/Knoisebridge.net.+013+33211
    }
    prometheus
    errors
  }
  noisebridge.org {
    file zones/noisebridge.org {
      # ns1.noisebridge.net (m3.noisebridge.net)
      transfer to 216.252.162.220
      transfer to 2602:ff06:725:5:dc::1337
      # ns2.noisebridge.net (m4.noisebridge.net)
      transfer to 204.246.122.84
      transfer to 2602:ff06:677:4:54::1337
    }
    prometheus
    errors
  }
  noisebridge.space {
    file zones/noisebridge.space {
      transfer to 104.131.134.47 # nicias.patrickod.com
      transfer to 204.246.122.84 # m2.noisebridge.net
      # transfer to 2604:a880:1:20::234:8001 # nicias.patrickod.com
    }
    dnssec noisebridge.space {
      key file keys/Knoisebridge.space.+013+22628
    }
    prometheus
    errors
  }
  noisetor.net {
    file zones/noisetor.net {
      # ns1.noisebridge.net (m3.noisebridge.net)
      transfer to 216.252.162.220
      transfer to 2602:ff06:725:5:dc::1337
      # ns2.noisebridge.net (m4.noisebridge.net)
      transfer to 204.246.122.84
      transfer to 2602:ff06:677:4:54::1337
    }
    prometheus
    errors
  }
