---
coredns_zone_files_paths:
- 'coredns/zones/*'
coredns_config_file: coredns/Corefile.primary.j2

noisebridge_dns_secondary_servers:
  # New ns2.noisebridge.net (m7.noisebridge.net)
  - '2600:3c0a::f03c:93ff:fe37:3d2f'
  - '172.232.171.61'

noisebridge_dns_primary_zones:
  - name: noisebridge.com
    file: noisebridge.com
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
  - name: noisebridge.io
    file: noisebridge.io
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
  - name: noisebridge.net
    file: noisebridge.net
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
    dnssec_key_file: 'Knoisebridge.net.+013+33211'
  - name: noisebridge.org
    file: noisebridge.org
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
  - name: noisetor.net
    file: noisetor.net
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
