---
collections:
- name: community.general
  type: galaxy
  version: ">=7.0.0"
- name: ansible.posix
  type: galaxy
  version: ">=1.5.0"
- name: prometheus.prometheus
  type: galaxy
  version: ">=0.5.0"
