---
- name: Install copy script
  ansible.builtin.copy:
    src: copy_certs.sh
    dest: /usr/local/sbin/copy_certs.sh
    owner: root
    group: root
    mode: 0755
  notify:
    - Restart caddy_certs.service

- name: Create cert directory
  ansible.builtin.file:
    path: "{{ caddy_certs_dest_path }}"
    state: directory
    owner: root
    group: ssl-cert
    mode: 0750

- name: Configure watch certs path
  ansible.builtin.template:
    src: caddy_certs.path.j2
    dest: /etc/systemd/system/caddy_certs.path
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload caddy_certs.path

- name: Configure copy certs service
  ansible.builtin.template:
    src: caddy_certs.service.j2
    dest: /etc/systemd/system/caddy_certs.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart caddy_certs.service

- name: Enable caddy_certs.path
  ansible.builtin.systemd:
    name: caddy_certs.path
    enabled: true

- name: Enable caddy_certs.service
  ansible.builtin.systemd:
    name: caddy_certs.service
    enabled: true
