---
node_exporter_system_group: ssl-cert
node_exporter_tls_server_config:
  cert_file: "/etc/ssl/{{ ansible_fqdn }}/{{ ansible_fqdn }}.crt"
  key_file: "/etc/ssl/{{ ansible_fqdn }}/{{ ansible_fqdn }}.key"

node_exporter_basic_auth_users:
  prometheus: "{{ noisebridge_prometheus_password }}"
