---
prometheus_web_listen_address: "127.0.0.1:9090"
prometheus_storage_retention: "90d"
prometheus_storage_retention_size: "5GB"
prometheus_config_flags_extra:
  query.max-samples: 10000000

prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s

prometheus_blackbox_relabel_configs:
- source_labels: [__address__]
  target_label: __param_target
- source_labels: [__param_target]
  target_label: instance
- target_label: __address__
  replacement: 127.0.0.1:9115

prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: "node"
    scheme: https
    basic_auth:
      username: prometheus
      password: "{{ noisebridge_prometheus_password }}"
    static_configs:
      - targets:
        - "m3.noisebridge.net:9100"
        - "m5.noisebridge.net:9100"
        - "m6.noisebridge.net:9100"
        - "m7.noisebridge.net:9100"
  - job_name: "caddy"
    scheme: https
    basic_auth:
      username: prometheus
      password: "{{ noisebridge_prometheus_password }}"
    static_configs:
      - targets:
        - "m3.noisebridge.net:443"
        - "m5.noisebridge.net:443"
        - "m6.noisebridge.net:443"
        - "m7.noisebridge.net:443"
  - job_name: "coredns"
    scheme: https
    metrics_path: /coredns/metrics
    basic_auth:
      username: prometheus
      password: "{{ noisebridge_prometheus_password }}"
    static_configs:
      - targets:
        - "m3.noisebridge.net:443"
        - "m7.noisebridge.net:443"
  - job_name: "donate"
    scheme: https
    static_configs:
      - targets:
        - "donate.noisebridge.net:443"
  - job_name: blackbox_http_v4
    metrics_path: /probe
    params:
      module: [http_2xx_v4]
    static_configs:
      - targets:
        - http://noisebridge.net
        - https://noisebridge.net
        - https://donate.noisebridge.net
        - https://library.noisebridge.net
        - https://lists.noisebridge.net
        - https://parts.noisebridge.net
    relabel_configs: "{{ prometheus_blackbox_relabel_configs }}"
  - job_name: blackbox_http_v6
    metrics_path: /probe
    params:
      module: [http_2xx_v6]
    static_configs:
      - targets:
        - http://noisebridge.net
        - https://noisebridge.net
        - https://donate.noisebridge.net
        - https://library.noisebridge.net
        - https://lists.noisebridge.net
        - https://parts.noisebridge.net
    relabel_configs: "{{ prometheus_blackbox_relabel_configs }}"
  - job_name: blackbox_smtp_v4
    metrics_path: /probe
    params:
      module: [smtp_starttls_v4]
    static_configs:
      - targets:
        - noisebridge.net:25
        - noisebridge.net:587
    relabel_configs: "{{ prometheus_blackbox_relabel_configs }}"
  - job_name: blackbox_smtp_v6
    metrics_path: /probe
    params:
      module: [smtp_starttls_v6]
    static_configs:
      - targets:
        - noisebridge.net:25
        - noisebridge.net:587
    relabel_configs: "{{ prometheus_blackbox_relabel_configs }}"
