---
- name: install php
  apt:
    update_cache: yes
    cache_valid_time: 3600
    package:
    - imagemagick
    - php7.3
    - php7.3-mysql
    - php7.3-imagick
    - php7.3-fpm
    - php7.3-mbstring
    - php7.3-xml
    - composer
  tags:
  - apt
  - php

- name: Configure PHP FPM
  copy:
    src: php/www.conf
    dest: /etc/php/7.3/fpm/pool.d/www.conf
    mode: 0644
  tags:
    - php
  notify:
    - restart php7.3-fpm
